import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.env.BUILD_ENV === 'production');

const copyPlugin = {
	name: 'copy-plugin',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				if (!fs.existsSync('dist')) {
					fs.mkdirSync('dist', { recursive: true });
				}
				if (fs.existsSync('manifest.json')) {
					fs.copyFileSync('manifest.json', path.join('dist', 'manifest.json'));
				}
				if (fs.existsSync('styles.css')) {
					fs.copyFileSync('styles.css', path.join('dist', 'styles.css'));
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'dist/main.js',
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
